### ISSUE TITLE
Provide multiple Cassandra contact points

### ISSUE THREAD

**Issue by cameronattard** [instaclustr/terraform-provider-instaclustr#66] opened 2021-02-12 01:14 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

From what I understand, best practice is to configure Cassandra clients with multiple contact points for the cluster. Currently the `instaclustr_cluster` resource can only return one contact point, meaning you would have to manually populate your client's contact points rather than directly using the output.

### New or Affected Resource(s)

* instaclustr_cluster

**Comment by slater-ben** [comment] 2021-02-12 02:33
Thanks for raising this. I've raised INS-12838 as our internal tracking ticket. We will update this issue when we have an ETA.

**Comment by cameronattard** [comment] 2021-02-15 02:18
Thanks @slater-ben, hope you're well!

**Comment by Chrismelba-Instaclustr** [comment] 2021-04-29 03:26
Hi there. This should be fixed in release 1.9.6! Thanks so much for bringing it to our attention. You can now get these details as private_contact_point or public_contact_point depending on your use case. It will return one IP per AZ.

**Comment by Chrismelba-Instaclustr** [comment] 2021-04-30 02:33
Just a quick note. For this to work as intended you'll need to add "wait_for_state="RUNNING"" to the clusters you wish to get the contact points for, as these IPs aren't known until the cluster is running

**Comment by cameronattard** [comment] 2021-05-03 03:14
Thanks @Chrismelba-Instaclustr, much appreciated!

**Closed** 2021-05-05 02:57 UTC
Labels: enhancement
